### ISSUE TITLE
mining success ，but get_mint_info not info

### ISSUE THREAD

**Issue by czdbX** [xrpinals/XrpinalsMintTool#4]

**Comment by xrpinals** [comment]
There could be many scenarios that could lead to such a problem, and it could be a result of some of the following:
- It is possible that the mint transaction constructed because of the network problem at that time was not successfully broadcast to the blockchain's block-producing node, so it resulted in the transaction not being successfully packaged into the block of the blockchain.
- Or the mint transaction did not pass the difficulty check of the blockchain node because it was at the threshold of difficulty adjustment, and so on.

**Comment by xrpinals** [comment]
Really appreciate with you for this issue, Thank a lot.
